name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
        cc: 1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
      with:
        version: 1.10.2
        platform: win

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CC: clang
        CCX: clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/build/JsonTestcase.exe
